flags: {}
packages:
- '.'
- location:
    git: https://www.github.com/mattjbray/elm-export
    commit: 3dfafc7a717003ff4374119ff6f60e5b56868d8f
  extra-dep: True
- location:
    git: https://www.github.com/mattjbray/servant-elm
    commit: 36c90557d17d237e621cdcb4912ae9e4f25a9e59
  extra-dep: True
extra-deps:
- aeson-0.11.1.4
- base-compat-0.9.1
- fast-logger-2.4.5
- wai-logger-2.2.7
- http2-1.6.0
- persistent-2.5
- persistent-postgresql-2.5
- persistent-template-2.5
- servant-0.5
- servant-foreign-0.5
- servant-server-0.5
- text-1.2.2.1
- warp-3.2.6
resolver: lts-5.11
