flags: {}
packages:
- '.'
extra-deps:
- aeson-0.11.1.4
- base-compat-0.9.1
- fast-logger-2.4.5
- wai-logger-2.2.7
- http2-1.6.0
- persistent-2.5
- persistent-postgresql-2.5
- persistent-template-2.5
- servant-0.7
- servant-server-0.7
- text-1.2.2.1
- warp-3.2.6
resolver: lts-5.11
